name: Word2GFM

on:
  push:
    branches: [ main ]

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
          
      - name: Create ODT
        uses: docker://ghcr.io/sandbox-coprs/importword:main
        with:
          args: bash -c "find . -type f -name '*.docx' -print0 | xargs -0 -n2 -P2 -I{} pandoc -s {} -t gfm --extract-media . -o {}.md"         

      - uses: actions/upload-artifact@master
        with:
          name: documentation
          path: |
            *.md
